// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.0.0
// 	protoc        v5.27.1
// source: models/player_model.proto

package models

import (
	fmt "fmt"
	delta "github.com/fixkme/gokit/db/mongo/delta"
	datas "github.com/fixkme/othello/server/pb/datas"
	reflect "reflect"
	strings "strings"
)

// @model
// 玩家数据
type MPlayerModel struct {
	playerId int64
	account  string
	// 玩家信息
	modelPlayerInfo *datas.MPlayerInfo
	// 正在游戏的桌子 PlayType => TableLocation
	inTables map[int64]*datas.MTableLocation

	// 自己本身的同步key,由父对象指定
	selfSyncID string
	// 本对象所有属性的同步key数组
	fieldSyncIDs [4]string
	// 收集字典,每帧清空同步
	collector delta.ICollector
	// 监测变化回调
	changedCb func(string)
}

// 构造函数
func NewMPlayerModel() *MPlayerModel {
	m := &MPlayerModel{}
	m.modelPlayerInfo = datas.NewMPlayerInfo()
	m.inTables = make(map[int64]*datas.MTableLocation)
	m.fieldSyncIDs[0] = "player_id"
	m.fieldSyncIDs[1] = "account"
	m.fieldSyncIDs[2] = "model_player_info"
	m.fieldSyncIDs[3] = "in_tables"
	return m
}

// PB构造函数
func NewPBPlayerModel() *PBPlayerModel {
	pb := &PBPlayerModel{}
	pb.ModelPlayerInfo = datas.NewPBPlayerInfo()
	pb.InTables = make(map[int64]*datas.PBTableLocation)
	return pb
}

// 设置collector函数
func (m *MPlayerModel) SetCollector(syncID string, collector delta.ICollector, cb func(string)) {
	m.selfSyncID = syncID
	m.collector = collector
	m.changedCb = cb
	if syncID != "" {
		syncID = syncID + "."
	}
	m.fieldSyncIDs[0] = syncID + "player_id"
	m.fieldSyncIDs[1] = syncID + "account"
	m.fieldSyncIDs[2] = syncID + "model_player_info"
	m.fieldSyncIDs[3] = syncID + "in_tables"
	m.modelPlayerInfo.SetCollector(m.fieldSyncIDs[2], collector, cb)
	for key, value := range m.inTables {
		syncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[3], key)
		value.SetCollector(syncKey, collector, cb)
	}
}

// 检查数值变化函数
func (m *MPlayerModel) checkDirty(valueOld any, valueNew any, key string, ntfClient bool) bool {
	if reflect.DeepEqual(valueOld, valueNew) {
		return false
	}
	if m.collector != nil {
		m.collector.Collect(key, valueNew, ntfClient)
	}
	if m.changedCb != nil {
		m.changedCb(key)
	}
	return true
}

// ToPB函数
func (m *MPlayerModel) ToPB() *PBPlayerModel {
	if m == nil {
		return nil
	}
	pb := NewPBPlayerModel()
	pb.PlayerId = m.playerId
	pb.Account = m.account
	pb.ModelPlayerInfo = m.modelPlayerInfo.ToPB()
	for key, value := range m.inTables {
		pb.InTables[key] = value.ToPB()
	}
	return pb
}

// InitFromPB函数
func (m *MPlayerModel) InitFromPB(pb *PBPlayerModel) {
	if pb == nil {
		return
	}
	m.playerId = pb.PlayerId
	m.account = pb.Account
	m.modelPlayerInfo.InitFromPB(pb.ModelPlayerInfo)
	for key, value := range pb.InTables {
		v := datas.NewMTableLocation()
		v.InitFromPB(value)
		m.inTables[key] = v
	}
}

// String 函数
func (m *MPlayerModel) String() string {
	var strBuilder strings.Builder
	strBuilder.WriteString("{")
	strBuilder.WriteString("playerId:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.playerId))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("account:")
	strBuilder.WriteString(fmt.Sprintf("%v", m.account))
	strBuilder.WriteString(", ")
	strBuilder.WriteString("modelPlayerInfo:")
	strBuilder.WriteString(m.modelPlayerInfo.String())
	strBuilder.WriteString(", ")
	strBuilder.WriteString("inTables:")
	strBuilder.WriteString("{")
	for key, value := range m.inTables {
		strBuilder.WriteString(fmt.Sprintf("%v:%s ", key, value.String()))
	}
	strBuilder.WriteString("}")
	strBuilder.WriteString("}")
	return strBuilder.String()
}

func (m *MPlayerModel) GetPlayerId() int64 {
	return m.playerId
}

func (m *MPlayerModel) SetPlayerId(value int64) {
	m.checkDirty(m.playerId, value, m.fieldSyncIDs[0], true)
	m.playerId = value
}

func (m *MPlayerModel) AddPlayerId(add int64) int64 {
	oldValue := m.playerId
	m.playerId += add
	m.checkDirty(oldValue, m.playerId, m.fieldSyncIDs[0], true)
	return m.playerId
}

func (m *MPlayerModel) GetAccount() string {
	return m.account
}

func (m *MPlayerModel) SetAccount(value string) {
	m.checkDirty(m.account, value, m.fieldSyncIDs[1], true)
	m.account = value
}

// 玩家信息
func (m *MPlayerModel) GetModelPlayerInfo() *datas.MPlayerInfo {
	return m.modelPlayerInfo
}

func (m *MPlayerModel) SetModelPlayerInfo(value *datas.MPlayerInfo) {
	if m.checkDirty(m.modelPlayerInfo, value, m.fieldSyncIDs[2], true) {
		value.SetCollector(m.fieldSyncIDs[2], m.collector, m.changedCb)
	}
	m.modelPlayerInfo = value
}

// 正在游戏的桌子 PlayType => TableLocation
func (m *MPlayerModel) GetInTables(key int64) (*datas.MTableLocation, bool) {
	value, exists := m.inTables[key]
	return value, exists
}

func (m *MPlayerModel) SetInTables(key int64, value *datas.MTableLocation) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[3], key)
	var oldValue any
	if v, ok := m.inTables[key]; ok {
		oldValue = v
	} else {
		oldValue = nil
	}
	if m.checkDirty(oldValue, value, localSyncKey, true) {
		value.SetCollector(localSyncKey, m.collector, m.changedCb)
	}
	m.inTables[key] = value
}

func (m *MPlayerModel) RemoveInTables(key int64) {
	localSyncKey := fmt.Sprintf("%s.%v", m.fieldSyncIDs[3], key)
	m.checkDirty(m.inTables[key], "__DELETE__", localSyncKey, true)
	delete(m.inTables, key)
}

func (m *MPlayerModel) ClearInTables() {
	for k := range m.inTables {
		m.RemoveInTables(k)
	}
}

func (m *MPlayerModel) GetInTablesCount() int64 {
	return int64(len(m.inTables))
}

// 正在游戏的桌子 PlayType => TableLocation
func (m *MPlayerModel) RangeInTables(f func(key int64, value *datas.MTableLocation) bool) {
	for k, v := range m.inTables {
		if !f(k, v) {
			return
		}
	}
}
