version: '3.8'

services:
  # gate
  gate:
    image: golang:local
    container_name: gate
    volumes:
      - ${APP_VOLUME}:/app
    ports:
      - "9091:9090"
      - "5000:2333"
      - "2201:2345" # 调试端口
    environment:
      - RPC_LISTEN_ADDR=:2333
      - RPC_ADDR=gate:2333
    command: ["./docker-compose/entrypoint.sh", "gate", "run"]
    depends_on:
      - etcd
  # game
  game:
    image: golang:local
    container_name: game
    volumes:
      - ${APP_VOLUME}:/app
    ports:
      - "5001:2333"
      - "2202:2345" # 调试端口
    environment:
      - RPC_LISTEN_ADDR=:2333
      - RPC_ADDR=game:2333
    command: ["./docker-compose/entrypoint.sh", "game", "run"]
    depends_on:
      - etcd
  # etcd 获取所有kv: docker exec -it etcd /usr/local/bin/etcdctl get "" --prefix
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    container_name: etcd
    volumes:
      - ${ETCD_DATA}:/etcd-data
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCDCTL_API=3
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data
      - --name=node1
      - --initial-advertise-peer-urls=http://0.0.0.0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=node1=http://0.0.0.0:2380