// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.27.1
// source: pbext/options_ext.proto

/* eslint-disable */

export const protobufPackage = "";
