// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.27.1
// source: models/player_model.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PlayerInfo } from "../datas/player_data";

export const protobufPackage = "models";

/**
 * @model
 * 玩家数据
 */
export interface PlayerModel {
  playerId: number;
  /** 玩家信息 */
  modelPlayerInfo: PlayerInfo | undefined;
}

function createBasePlayerModel(): PlayerModel {
  return { playerId: 0, modelPlayerInfo: undefined };
}

export const PlayerModel: MessageFns<PlayerModel> = {
  encode(message: PlayerModel, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerId !== 0) {
      writer.uint32(8).int64(message.playerId);
    }
    if (message.modelPlayerInfo !== undefined) {
      PlayerInfo.encode(message.modelPlayerInfo, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerModel {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerModel();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.playerId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.modelPlayerInfo = PlayerInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerModel {
    return {
      playerId: isSet(object.playerId) ? globalThis.Number(object.playerId) : 0,
      modelPlayerInfo: isSet(object.modelPlayerInfo) ? PlayerInfo.fromJSON(object.modelPlayerInfo) : undefined,
    };
  },

  toJSON(message: PlayerModel): unknown {
    const obj: any = {};
    if (message.playerId !== 0) {
      obj.playerId = Math.round(message.playerId);
    }
    if (message.modelPlayerInfo !== undefined) {
      obj.modelPlayerInfo = PlayerInfo.toJSON(message.modelPlayerInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerModel>, I>>(base?: I): PlayerModel {
    return PlayerModel.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerModel>, I>>(object: I): PlayerModel {
    const message = createBasePlayerModel();
    message.playerId = object.playerId ?? 0;
    message.modelPlayerInfo = (object.modelPlayerInfo !== undefined && object.modelPlayerInfo !== null)
      ? PlayerInfo.fromPartial(object.modelPlayerInfo)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
