// Code generated by protoc-gen-gom. DO NOT EDIT.
package game

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type GameServer interface {
	CreateRoom(context.Context, *CCreateRoom) (*SCreateRoom, error)
	EnterGame(context.Context, *CEnterGame) (*SEnterGame, error)
	LeaveGame(context.Context, *CLeaveGame) (*SLeaveGame, error)
	PlacePiece(context.Context, *CPlacePiece) (*SPlacePiece, error)
	PlayerOffline(context.Context, *CPlayerOffline) (*SPlayerOffline, error)
	ReadyGame(context.Context, *CReadyGame) (*SReadyGame, error)
}

func RegisterGameServer(s rpc.ServiceRegistrar, srv GameServer) {
	s.RegisterService(&Game_ServiceDesc, srv)
}

func _Game_CreateRoom_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CCreateRoom)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).CreateRoom(ctx, req.(*CCreateRoom))
	}
	return arg, h
}

func _Game_EnterGame_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CEnterGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).EnterGame(ctx, req.(*CEnterGame))
	}
	return arg, h
}

func _Game_LeaveGame_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CLeaveGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).LeaveGame(ctx, req.(*CLeaveGame))
	}
	return arg, h
}

func _Game_PlacePiece_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CPlacePiece)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).PlacePiece(ctx, req.(*CPlacePiece))
	}
	return arg, h
}

func _Game_PlayerOffline_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CPlayerOffline)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).PlayerOffline(ctx, req.(*CPlayerOffline))
	}
	return arg, h
}

func _Game_ReadyGame_Materializer(srv any) (proto.Message, rpc.MsgHandler) {
	arg := new(CReadyGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(GameServer).ReadyGame(ctx, req.(*CReadyGame))
	}
	return arg, h
}

var Game_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "game",
	HandlerType: (*GameServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _Game_CreateRoom_Materializer,
		},
		{
			MethodName: "EnterGame",
			Handler:    _Game_EnterGame_Materializer,
		},
		{
			MethodName: "LeaveGame",
			Handler:    _Game_LeaveGame_Materializer,
		},
		{
			MethodName: "PlacePiece",
			Handler:    _Game_PlacePiece_Materializer,
		},
		{
			MethodName: "PlayerOffline",
			Handler:    _Game_PlayerOffline_Materializer,
		},
		{
			MethodName: "ReadyGame",
			Handler:    _Game_ReadyGame_Materializer,
		},
	},
}
