// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: game/player.proto

package game

import (
	models "github.com/fixkme/othello/server/pb/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLogin) Reset() {
	*x = CLogin{}
	mi := &file_game_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLogin) ProtoMessage() {}

func (x *CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLogin.ProtoReflect.Descriptor instead.
func (*CLogin) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{0}
}

func (x *CLogin) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerData    *models.PBPlayerModel  `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	ServerTz      int64                  `protobuf:"varint,2,opt,name=server_tz,json=serverTz,proto3" json:"server_tz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLogin) Reset() {
	*x = SLogin{}
	mi := &file_game_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLogin) ProtoMessage() {}

func (x *SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLogin.ProtoReflect.Descriptor instead.
func (*SLogin) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{1}
}

func (x *SLogin) GetPlayerData() *models.PBPlayerModel {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *SLogin) GetServerTz() int64 {
	if x != nil {
		return x.ServerTz
	}
	return 0
}

var File_game_player_proto protoreflect.FileDescriptor

const file_game_player_proto_rawDesc = "" +
	"\n" +
	"\x11game/player.proto\x12\x04game\x1a\x19models/player_model.proto\"%\n" +
	"\x06CLogin\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"[\n" +
	"\x06SLogin\x124\n" +
	"\vplayer_data\x18\x01 \x01(\v2\x13.models.PlayerModelR\n" +
	"playerData\x12\x1b\n" +
	"\tserver_tz\x18\x02 \x01(\x03R\bserverTzB*Z(github.com/fixkme/othello/server/pb/gameb\x06proto3"

var (
	file_game_player_proto_rawDescOnce sync.Once
	file_game_player_proto_rawDescData []byte
)

func file_game_player_proto_rawDescGZIP() []byte {
	file_game_player_proto_rawDescOnce.Do(func() {
		file_game_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_player_proto_rawDesc), len(file_game_player_proto_rawDesc)))
	})
	return file_game_player_proto_rawDescData
}

var file_game_player_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_player_proto_goTypes = []any{
	(*CLogin)(nil),               // 0: game.CLogin
	(*SLogin)(nil),               // 1: game.SLogin
	(*models.PBPlayerModel)(nil), // 2: models.PlayerModel
}
var file_game_player_proto_depIdxs = []int32{
	2, // 0: game.SLogin.player_data:type_name -> models.PlayerModel
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_player_proto_init() }
func file_game_player_proto_init() {
	if File_game_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_player_proto_rawDesc), len(file_game_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_player_proto_goTypes,
		DependencyIndexes: file_game_player_proto_depIdxs,
		MessageInfos:      file_game_player_proto_msgTypes,
	}.Build()
	File_game_player_proto = out.File
	file_game_player_proto_goTypes = nil
	file_game_player_proto_depIdxs = nil
}
