// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: game/player.proto

package game

import (
	datas "github.com/fixkme/othello/server/pb/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PReadyGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableInfo     *datas.PBTableInfo     `protobuf:"bytes,1,opt,name=table_info,json=tableInfo,proto3" json:"table_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PReadyGame) Reset() {
	*x = PReadyGame{}
	mi := &file_game_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PReadyGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PReadyGame) ProtoMessage() {}

func (x *PReadyGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PReadyGame.ProtoReflect.Descriptor instead.
func (*PReadyGame) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{0}
}

func (x *PReadyGame) GetTableInfo() *datas.PBTableInfo {
	if x != nil {
		return x.TableInfo
	}
	return nil
}

type CReadyGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CReadyGame) Reset() {
	*x = CReadyGame{}
	mi := &file_game_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CReadyGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CReadyGame) ProtoMessage() {}

func (x *CReadyGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CReadyGame.ProtoReflect.Descriptor instead.
func (*CReadyGame) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{1}
}

type SReadyGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SReadyGame) Reset() {
	*x = SReadyGame{}
	mi := &file_game_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SReadyGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SReadyGame) ProtoMessage() {}

func (x *SReadyGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SReadyGame.ProtoReflect.Descriptor instead.
func (*SReadyGame) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{2}
}

type PStartGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PStartGame) Reset() {
	*x = PStartGame{}
	mi := &file_game_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PStartGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PStartGame) ProtoMessage() {}

func (x *PStartGame) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PStartGame.ProtoReflect.Descriptor instead.
func (*PStartGame) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{3}
}

type CPlacePiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceType     int32                  `protobuf:"varint,1,opt,name=piece_type,json=pieceType,proto3" json:"piece_type,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPlacePiece) Reset() {
	*x = CPlacePiece{}
	mi := &file_game_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPlacePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPlacePiece) ProtoMessage() {}

func (x *CPlacePiece) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPlacePiece.ProtoReflect.Descriptor instead.
func (*CPlacePiece) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{4}
}

func (x *CPlacePiece) GetPieceType() int32 {
	if x != nil {
		return x.PieceType
	}
	return 0
}

func (x *CPlacePiece) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CPlacePiece) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SPlacePiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPlacePiece) Reset() {
	*x = SPlacePiece{}
	mi := &file_game_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPlacePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPlacePiece) ProtoMessage() {}

func (x *SPlacePiece) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPlacePiece.ProtoReflect.Descriptor instead.
func (*SPlacePiece) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{5}
}

type PPlacePiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PieceType     int32                  `protobuf:"varint,1,opt,name=piece_type,json=pieceType,proto3" json:"piece_type,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	OperatePiece  int32                  `protobuf:"varint,4,opt,name=operate_piece,json=operatePiece,proto3" json:"operate_piece,omitempty"` //当前操作的棋子
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPlacePiece) Reset() {
	*x = PPlacePiece{}
	mi := &file_game_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPlacePiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPlacePiece) ProtoMessage() {}

func (x *PPlacePiece) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPlacePiece.ProtoReflect.Descriptor instead.
func (*PPlacePiece) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{6}
}

func (x *PPlacePiece) GetPieceType() int32 {
	if x != nil {
		return x.PieceType
	}
	return 0
}

func (x *PPlacePiece) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PPlacePiece) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PPlacePiece) GetOperatePiece() int32 {
	if x != nil {
		return x.OperatePiece
	}
	return 0
}

type PGameResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WinnerPieceType int64                  `protobuf:"varint,1,opt,name=winner_piece_type,json=winnerPieceType,proto3" json:"winner_piece_type,omitempty"`
	LoserPieceType  int64                  `protobuf:"varint,2,opt,name=loser_piece_type,json=loserPieceType,proto3" json:"loser_piece_type,omitempty"`
	IsGiveUp        bool                   `protobuf:"varint,3,opt,name=is_give_up,json=isGiveUp,proto3" json:"is_give_up,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PGameResult) Reset() {
	*x = PGameResult{}
	mi := &file_game_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGameResult) ProtoMessage() {}

func (x *PGameResult) ProtoReflect() protoreflect.Message {
	mi := &file_game_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGameResult.ProtoReflect.Descriptor instead.
func (*PGameResult) Descriptor() ([]byte, []int) {
	return file_game_player_proto_rawDescGZIP(), []int{7}
}

func (x *PGameResult) GetWinnerPieceType() int64 {
	if x != nil {
		return x.WinnerPieceType
	}
	return 0
}

func (x *PGameResult) GetLoserPieceType() int64 {
	if x != nil {
		return x.LoserPieceType
	}
	return 0
}

func (x *PGameResult) GetIsGiveUp() bool {
	if x != nil {
		return x.IsGiveUp
	}
	return false
}

var File_game_player_proto protoreflect.FileDescriptor

const file_game_player_proto_rawDesc = "" +
	"\n" +
	"\x11game/player.proto\x12\x04game\x1a\x17datas/player_data.proto\"=\n" +
	"\n" +
	"PReadyGame\x12/\n" +
	"\n" +
	"table_info\x18\x01 \x01(\v2\x10.datas.TableInfoR\ttableInfo\"\f\n" +
	"\n" +
	"CReadyGame\"\f\n" +
	"\n" +
	"SReadyGame\"\f\n" +
	"\n" +
	"PStartGame\"H\n" +
	"\vCPlacePiece\x12\x1d\n" +
	"\n" +
	"piece_type\x18\x01 \x01(\x05R\tpieceType\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\r\n" +
	"\vSPlacePiece\"m\n" +
	"\vPPlacePiece\x12\x1d\n" +
	"\n" +
	"piece_type\x18\x01 \x01(\x05R\tpieceType\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12#\n" +
	"\roperate_piece\x18\x04 \x01(\x05R\foperatePiece\"\x81\x01\n" +
	"\vPGameResult\x12*\n" +
	"\x11winner_piece_type\x18\x01 \x01(\x03R\x0fwinnerPieceType\x12(\n" +
	"\x10loser_piece_type\x18\x02 \x01(\x03R\x0eloserPieceType\x12\x1c\n" +
	"\n" +
	"is_give_up\x18\x03 \x01(\bR\bisGiveUpB*Z(github.com/fixkme/othello/server/pb/gameb\x06proto3"

var (
	file_game_player_proto_rawDescOnce sync.Once
	file_game_player_proto_rawDescData []byte
)

func file_game_player_proto_rawDescGZIP() []byte {
	file_game_player_proto_rawDescOnce.Do(func() {
		file_game_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_player_proto_rawDesc), len(file_game_player_proto_rawDesc)))
	})
	return file_game_player_proto_rawDescData
}

var file_game_player_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_game_player_proto_goTypes = []any{
	(*PReadyGame)(nil),        // 0: game.PReadyGame
	(*CReadyGame)(nil),        // 1: game.CReadyGame
	(*SReadyGame)(nil),        // 2: game.SReadyGame
	(*PStartGame)(nil),        // 3: game.PStartGame
	(*CPlacePiece)(nil),       // 4: game.CPlacePiece
	(*SPlacePiece)(nil),       // 5: game.SPlacePiece
	(*PPlacePiece)(nil),       // 6: game.PPlacePiece
	(*PGameResult)(nil),       // 7: game.PGameResult
	(*datas.PBTableInfo)(nil), // 8: datas.TableInfo
}
var file_game_player_proto_depIdxs = []int32{
	8, // 0: game.PReadyGame.table_info:type_name -> datas.TableInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_player_proto_init() }
func file_game_player_proto_init() {
	if File_game_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_player_proto_rawDesc), len(file_game_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_player_proto_goTypes,
		DependencyIndexes: file_game_player_proto_depIdxs,
		MessageInfos:      file_game_player_proto_msgTypes,
	}.Build()
	File_game_player_proto = out.File
	file_game_player_proto_goTypes = nil
	file_game_player_proto_depIdxs = nil
}
