// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: ws/ws.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBPackage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 消息类型
	MessageType string `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// 数据
	MessagePayload []byte `protobuf:"bytes,2,opt,name=message_payload,json=messagePayload,proto3" json:"message_payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PBPackage) Reset() {
	*x = PBPackage{}
	mi := &file_ws_ws_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBPackage) ProtoMessage() {}

func (x *PBPackage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBPackage.ProtoReflect.Descriptor instead.
func (*PBPackage) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{0}
}

func (x *PBPackage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PBPackage) GetMessagePayload() []byte {
	if x != nil {
		return x.MessagePayload
	}
	return nil
}

type WsRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`       // 消息的唯一id
	MsgName       string                 `protobuf:"bytes,2,opt,name=msgName,proto3" json:"msgName,omitempty"` // request的消息名，game.CLogin
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // 数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsRequestMessage) Reset() {
	*x = WsRequestMessage{}
	mi := &file_ws_ws_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsRequestMessage) ProtoMessage() {}

func (x *WsRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsRequestMessage.ProtoReflect.Descriptor instead.
func (*WsRequestMessage) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{1}
}

func (x *WsRequestMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WsRequestMessage) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *WsRequestMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type WsResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                             // 和request的uuid对应
	MsgName       string                 `protobuf:"bytes,2,opt,name=msgName,proto3" json:"msgName,omitempty"`                       // response的消息名，game.SLogin
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                       // 数据
	ErrorCode     int32                  `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"` // 错误码, >0 表示错误
	ErrorDesc     string                 `protobuf:"bytes,5,opt,name=error_desc,json=errorDesc,proto3" json:"error_desc,omitempty"`  // 错误描述, error_code>0时有效
	Notices       []*PBPackage           `protobuf:"bytes,6,rep,name=notices,proto3" json:"notices,omitempty"`                       // 回应带下的推送消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsResponseMessage) Reset() {
	*x = WsResponseMessage{}
	mi := &file_ws_ws_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsResponseMessage) ProtoMessage() {}

func (x *WsResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsResponseMessage.ProtoReflect.Descriptor instead.
func (*WsResponseMessage) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{2}
}

func (x *WsResponseMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *WsResponseMessage) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *WsResponseMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WsResponseMessage) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *WsResponseMessage) GetErrorDesc() string {
	if x != nil {
		return x.ErrorDesc
	}
	return ""
}

func (x *WsResponseMessage) GetNotices() []*PBPackage {
	if x != nil {
		return x.Notices
	}
	return nil
}

type WsPushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notices       []*PBPackage           `protobuf:"bytes,1,rep,name=notices,proto3" json:"notices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WsPushMessage) Reset() {
	*x = WsPushMessage{}
	mi := &file_ws_ws_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WsPushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WsPushMessage) ProtoMessage() {}

func (x *WsPushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ws_ws_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WsPushMessage.ProtoReflect.Descriptor instead.
func (*WsPushMessage) Descriptor() ([]byte, []int) {
	return file_ws_ws_proto_rawDescGZIP(), []int{3}
}

func (x *WsPushMessage) GetNotices() []*PBPackage {
	if x != nil {
		return x.Notices
	}
	return nil
}

var File_ws_ws_proto protoreflect.FileDescriptor

const file_ws_ws_proto_rawDesc = "" +
	"\n" +
	"\vws/ws.proto\x12\x02ws\"W\n" +
	"\tPBPackage\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12'\n" +
	"\x0fmessage_payload\x18\x02 \x01(\fR\x0emessagePayload\"Z\n" +
	"\x10WsRequestMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\amsgName\x18\x02 \x01(\tR\amsgName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xc2\x01\n" +
	"\x11WsResponseMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\amsgName\x18\x02 \x01(\tR\amsgName\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x05R\terrorCode\x12\x1d\n" +
	"\n" +
	"error_desc\x18\x05 \x01(\tR\terrorDesc\x12'\n" +
	"\anotices\x18\x06 \x03(\v2\r.ws.PBPackageR\anotices\"8\n" +
	"\rWsPushMessage\x12'\n" +
	"\anotices\x18\x01 \x03(\v2\r.ws.PBPackageR\anoticesB(Z&github.com/fixkme/othello/server/pb/wsb\x06proto3"

var (
	file_ws_ws_proto_rawDescOnce sync.Once
	file_ws_ws_proto_rawDescData []byte
)

func file_ws_ws_proto_rawDescGZIP() []byte {
	file_ws_ws_proto_rawDescOnce.Do(func() {
		file_ws_ws_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ws_ws_proto_rawDesc), len(file_ws_ws_proto_rawDesc)))
	})
	return file_ws_ws_proto_rawDescData
}

var file_ws_ws_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ws_ws_proto_goTypes = []any{
	(*PBPackage)(nil),         // 0: ws.PBPackage
	(*WsRequestMessage)(nil),  // 1: ws.WsRequestMessage
	(*WsResponseMessage)(nil), // 2: ws.WsResponseMessage
	(*WsPushMessage)(nil),     // 3: ws.WsPushMessage
}
var file_ws_ws_proto_depIdxs = []int32{
	0, // 0: ws.WsResponseMessage.notices:type_name -> ws.PBPackage
	0, // 1: ws.WsPushMessage.notices:type_name -> ws.PBPackage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ws_ws_proto_init() }
func file_ws_ws_proto_init() {
	if File_ws_ws_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ws_ws_proto_rawDesc), len(file_ws_ws_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ws_ws_proto_goTypes,
		DependencyIndexes: file_ws_ws_proto_depIdxs,
		MessageInfos:      file_ws_ws_proto_msgTypes,
	}.Build()
	File_ws_ws_proto = out.File
	file_ws_ws_proto_goTypes = nil
	file_ws_ws_proto_depIdxs = nil
}
