// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.27.1
// source: game/player.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PlayerInfo, TableInfo } from "../datas/player_data";
import { PlayerModel } from "../models/player_model";
import { messageTypeRegistry } from "../typeRegistry";

export const protobufPackage = "game";

export interface CLogin {
  $type: "game.CLogin";
  playerId: number;
}

export interface SLogin {
  $type: "game.SLogin";
  playerData: PlayerModel | undefined;
  serverTz: number;
}

export interface CEnterGame {
  $type: "game.CEnterGame";
}

export interface SEnterGame {
  $type: "game.SEnterGame";
  tableInfo: TableInfo | undefined;
}

export interface PPlayerEnterGame {
  $type: "game.PPlayerEnterGame";
  playerInfo: PlayerInfo | undefined;
}

export interface CPlacePiece {
  $type: "game.CPlacePiece";
  pieceType: number;
  x: number;
  y: number;
}

export interface SPlacePiece {
  $type: "game.SPlacePiece";
}

export interface PPlacePiece {
  $type: "game.PPlacePiece";
  pieceType: number;
  x: number;
  y: number;
}

function createBaseCLogin(): CLogin {
  return { $type: "game.CLogin", playerId: 0 };
}

export const CLogin: MessageFns<CLogin, "game.CLogin"> = {
  $type: "game.CLogin" as const,

  encode(message: CLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerId !== 0) {
      writer.uint32(8).int64(message.playerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.playerId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CLogin {
    return { $type: CLogin.$type, playerId: isSet(object.playerId) ? globalThis.Number(object.playerId) : 0 };
  },

  toJSON(message: CLogin): unknown {
    const obj: any = {};
    if (message.playerId !== 0) {
      obj.playerId = Math.round(message.playerId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CLogin>, I>>(base?: I): CLogin {
    return CLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CLogin>, I>>(object: I): CLogin {
    const message = createBaseCLogin();
    message.playerId = object.playerId ?? 0;
    return message;
  },
};

messageTypeRegistry.set(CLogin.$type, CLogin);

function createBaseSLogin(): SLogin {
  return { $type: "game.SLogin", playerData: undefined, serverTz: 0 };
}

export const SLogin: MessageFns<SLogin, "game.SLogin"> = {
  $type: "game.SLogin" as const,

  encode(message: SLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerData !== undefined) {
      PlayerModel.encode(message.playerData, writer.uint32(10).fork()).join();
    }
    if (message.serverTz !== 0) {
      writer.uint32(16).int64(message.serverTz);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerData = PlayerModel.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serverTz = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SLogin {
    return {
      $type: SLogin.$type,
      playerData: isSet(object.playerData) ? PlayerModel.fromJSON(object.playerData) : undefined,
      serverTz: isSet(object.serverTz) ? globalThis.Number(object.serverTz) : 0,
    };
  },

  toJSON(message: SLogin): unknown {
    const obj: any = {};
    if (message.playerData !== undefined) {
      obj.playerData = PlayerModel.toJSON(message.playerData);
    }
    if (message.serverTz !== 0) {
      obj.serverTz = Math.round(message.serverTz);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SLogin>, I>>(base?: I): SLogin {
    return SLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SLogin>, I>>(object: I): SLogin {
    const message = createBaseSLogin();
    message.playerData = (object.playerData !== undefined && object.playerData !== null)
      ? PlayerModel.fromPartial(object.playerData)
      : undefined;
    message.serverTz = object.serverTz ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SLogin.$type, SLogin);

function createBaseCEnterGame(): CEnterGame {
  return { $type: "game.CEnterGame" };
}

export const CEnterGame: MessageFns<CEnterGame, "game.CEnterGame"> = {
  $type: "game.CEnterGame" as const,

  encode(_: CEnterGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CEnterGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCEnterGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CEnterGame {
    return { $type: CEnterGame.$type };
  },

  toJSON(_: CEnterGame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CEnterGame>, I>>(base?: I): CEnterGame {
    return CEnterGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CEnterGame>, I>>(_: I): CEnterGame {
    const message = createBaseCEnterGame();
    return message;
  },
};

messageTypeRegistry.set(CEnterGame.$type, CEnterGame);

function createBaseSEnterGame(): SEnterGame {
  return { $type: "game.SEnterGame", tableInfo: undefined };
}

export const SEnterGame: MessageFns<SEnterGame, "game.SEnterGame"> = {
  $type: "game.SEnterGame" as const,

  encode(message: SEnterGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tableInfo !== undefined) {
      TableInfo.encode(message.tableInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SEnterGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSEnterGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tableInfo = TableInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SEnterGame {
    return {
      $type: SEnterGame.$type,
      tableInfo: isSet(object.tableInfo) ? TableInfo.fromJSON(object.tableInfo) : undefined,
    };
  },

  toJSON(message: SEnterGame): unknown {
    const obj: any = {};
    if (message.tableInfo !== undefined) {
      obj.tableInfo = TableInfo.toJSON(message.tableInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SEnterGame>, I>>(base?: I): SEnterGame {
    return SEnterGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SEnterGame>, I>>(object: I): SEnterGame {
    const message = createBaseSEnterGame();
    message.tableInfo = (object.tableInfo !== undefined && object.tableInfo !== null)
      ? TableInfo.fromPartial(object.tableInfo)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(SEnterGame.$type, SEnterGame);

function createBasePPlayerEnterGame(): PPlayerEnterGame {
  return { $type: "game.PPlayerEnterGame", playerInfo: undefined };
}

export const PPlayerEnterGame: MessageFns<PPlayerEnterGame, "game.PPlayerEnterGame"> = {
  $type: "game.PPlayerEnterGame" as const,

  encode(message: PPlayerEnterGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerInfo !== undefined) {
      PlayerInfo.encode(message.playerInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PPlayerEnterGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePPlayerEnterGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerInfo = PlayerInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PPlayerEnterGame {
    return {
      $type: PPlayerEnterGame.$type,
      playerInfo: isSet(object.playerInfo) ? PlayerInfo.fromJSON(object.playerInfo) : undefined,
    };
  },

  toJSON(message: PPlayerEnterGame): unknown {
    const obj: any = {};
    if (message.playerInfo !== undefined) {
      obj.playerInfo = PlayerInfo.toJSON(message.playerInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PPlayerEnterGame>, I>>(base?: I): PPlayerEnterGame {
    return PPlayerEnterGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PPlayerEnterGame>, I>>(object: I): PPlayerEnterGame {
    const message = createBasePPlayerEnterGame();
    message.playerInfo = (object.playerInfo !== undefined && object.playerInfo !== null)
      ? PlayerInfo.fromPartial(object.playerInfo)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(PPlayerEnterGame.$type, PPlayerEnterGame);

function createBaseCPlacePiece(): CPlacePiece {
  return { $type: "game.CPlacePiece", pieceType: 0, x: 0, y: 0 };
}

export const CPlacePiece: MessageFns<CPlacePiece, "game.CPlacePiece"> = {
  $type: "game.CPlacePiece" as const,

  encode(message: CPlacePiece, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceType !== 0) {
      writer.uint32(8).int32(message.pieceType);
    }
    if (message.x !== 0) {
      writer.uint32(16).int32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(24).int32(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CPlacePiece {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCPlacePiece();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pieceType = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.x = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.y = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CPlacePiece {
    return {
      $type: CPlacePiece.$type,
      pieceType: isSet(object.pieceType) ? globalThis.Number(object.pieceType) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: CPlacePiece): unknown {
    const obj: any = {};
    if (message.pieceType !== 0) {
      obj.pieceType = Math.round(message.pieceType);
    }
    if (message.x !== 0) {
      obj.x = Math.round(message.x);
    }
    if (message.y !== 0) {
      obj.y = Math.round(message.y);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CPlacePiece>, I>>(base?: I): CPlacePiece {
    return CPlacePiece.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CPlacePiece>, I>>(object: I): CPlacePiece {
    const message = createBaseCPlacePiece();
    message.pieceType = object.pieceType ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

messageTypeRegistry.set(CPlacePiece.$type, CPlacePiece);

function createBaseSPlacePiece(): SPlacePiece {
  return { $type: "game.SPlacePiece" };
}

export const SPlacePiece: MessageFns<SPlacePiece, "game.SPlacePiece"> = {
  $type: "game.SPlacePiece" as const,

  encode(_: SPlacePiece, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SPlacePiece {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSPlacePiece();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SPlacePiece {
    return { $type: SPlacePiece.$type };
  },

  toJSON(_: SPlacePiece): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SPlacePiece>, I>>(base?: I): SPlacePiece {
    return SPlacePiece.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SPlacePiece>, I>>(_: I): SPlacePiece {
    const message = createBaseSPlacePiece();
    return message;
  },
};

messageTypeRegistry.set(SPlacePiece.$type, SPlacePiece);

function createBasePPlacePiece(): PPlacePiece {
  return { $type: "game.PPlacePiece", pieceType: 0, x: 0, y: 0 };
}

export const PPlacePiece: MessageFns<PPlacePiece, "game.PPlacePiece"> = {
  $type: "game.PPlacePiece" as const,

  encode(message: PPlacePiece, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pieceType !== 0) {
      writer.uint32(8).int32(message.pieceType);
    }
    if (message.x !== 0) {
      writer.uint32(16).int32(message.x);
    }
    if (message.y !== 0) {
      writer.uint32(24).int32(message.y);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PPlacePiece {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePPlacePiece();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.pieceType = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.x = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.y = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PPlacePiece {
    return {
      $type: PPlacePiece.$type,
      pieceType: isSet(object.pieceType) ? globalThis.Number(object.pieceType) : 0,
      x: isSet(object.x) ? globalThis.Number(object.x) : 0,
      y: isSet(object.y) ? globalThis.Number(object.y) : 0,
    };
  },

  toJSON(message: PPlacePiece): unknown {
    const obj: any = {};
    if (message.pieceType !== 0) {
      obj.pieceType = Math.round(message.pieceType);
    }
    if (message.x !== 0) {
      obj.x = Math.round(message.x);
    }
    if (message.y !== 0) {
      obj.y = Math.round(message.y);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PPlacePiece>, I>>(base?: I): PPlacePiece {
    return PPlacePiece.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PPlacePiece>, I>>(object: I): PPlacePiece {
    const message = createBasePPlacePiece();
    message.pieceType = object.pieceType ?? 0;
    message.x = object.x ?? 0;
    message.y = object.y ?? 0;
    return message;
  },
};

messageTypeRegistry.set(PPlacePiece.$type, PPlacePiece);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
