// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: hall/hall_ss.proto

package hall

import (
	datas "github.com/fixkme/othello/server/pb/datas"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CPlayerOffline) Reset() {
	*x = CPlayerOffline{}
	mi := &file_hall_hall_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPlayerOffline) ProtoMessage() {}

func (x *CPlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_hall_hall_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPlayerOffline.ProtoReflect.Descriptor instead.
func (*CPlayerOffline) Descriptor() ([]byte, []int) {
	return file_hall_hall_ss_proto_rawDescGZIP(), []int{0}
}

func (x *CPlayerOffline) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type SPlayerOffline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SPlayerOffline) Reset() {
	*x = SPlayerOffline{}
	mi := &file_hall_hall_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPlayerOffline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPlayerOffline) ProtoMessage() {}

func (x *SPlayerOffline) ProtoReflect() protoreflect.Message {
	mi := &file_hall_hall_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPlayerOffline.ProtoReflect.Descriptor instead.
func (*SPlayerOffline) Descriptor() ([]byte, []int) {
	return file_hall_hall_ss_proto_rawDescGZIP(), []int{1}
}

type CGameSettle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerPlayer   *datas.PBPlayerInfo    `protobuf:"bytes,1,opt,name=owner_player,json=ownerPlayer,proto3" json:"owner_player,omitempty"`
	OppoPlayer    *datas.PBPlayerInfo    `protobuf:"bytes,2,opt,name=oppo_player,json=oppoPlayer,proto3" json:"oppo_player,omitempty"`
	TableId       int64                  `protobuf:"varint,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	WinPlayer     int64                  `protobuf:"varint,6,opt,name=win_player,json=winPlayer,proto3" json:"win_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CGameSettle) Reset() {
	*x = CGameSettle{}
	mi := &file_hall_hall_ss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CGameSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CGameSettle) ProtoMessage() {}

func (x *CGameSettle) ProtoReflect() protoreflect.Message {
	mi := &file_hall_hall_ss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CGameSettle.ProtoReflect.Descriptor instead.
func (*CGameSettle) Descriptor() ([]byte, []int) {
	return file_hall_hall_ss_proto_rawDescGZIP(), []int{2}
}

func (x *CGameSettle) GetOwnerPlayer() *datas.PBPlayerInfo {
	if x != nil {
		return x.OwnerPlayer
	}
	return nil
}

func (x *CGameSettle) GetOppoPlayer() *datas.PBPlayerInfo {
	if x != nil {
		return x.OppoPlayer
	}
	return nil
}

func (x *CGameSettle) GetTableId() int64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *CGameSettle) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CGameSettle) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CGameSettle) GetWinPlayer() int64 {
	if x != nil {
		return x.WinPlayer
	}
	return 0
}

type SGameSettle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SGameSettle) Reset() {
	*x = SGameSettle{}
	mi := &file_hall_hall_ss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SGameSettle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGameSettle) ProtoMessage() {}

func (x *SGameSettle) ProtoReflect() protoreflect.Message {
	mi := &file_hall_hall_ss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGameSettle.ProtoReflect.Descriptor instead.
func (*SGameSettle) Descriptor() ([]byte, []int) {
	return file_hall_hall_ss_proto_rawDescGZIP(), []int{3}
}

var File_hall_hall_ss_proto protoreflect.FileDescriptor

const file_hall_hall_ss_proto_rawDesc = "" +
	"\n" +
	"\x12hall/hall_ss.proto\x12\x04hall\x1a\x17datas/player_data.proto\"-\n" +
	"\x0eCPlayerOffline\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x10\n" +
	"\x0eSPlayerOffline\"\xeb\x01\n" +
	"\vCGameSettle\x124\n" +
	"\fowner_player\x18\x01 \x01(\v2\x11.datas.PlayerInfoR\vownerPlayer\x122\n" +
	"\voppo_player\x18\x02 \x01(\v2\x11.datas.PlayerInfoR\n" +
	"oppoPlayer\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\x03R\atableId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"win_player\x18\x06 \x01(\x03R\twinPlayer\"\r\n" +
	"\vSGameSettleB*Z(github.com/fixkme/othello/server/pb/hallb\x06proto3"

var (
	file_hall_hall_ss_proto_rawDescOnce sync.Once
	file_hall_hall_ss_proto_rawDescData []byte
)

func file_hall_hall_ss_proto_rawDescGZIP() []byte {
	file_hall_hall_ss_proto_rawDescOnce.Do(func() {
		file_hall_hall_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hall_hall_ss_proto_rawDesc), len(file_hall_hall_ss_proto_rawDesc)))
	})
	return file_hall_hall_ss_proto_rawDescData
}

var file_hall_hall_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hall_hall_ss_proto_goTypes = []any{
	(*CPlayerOffline)(nil),     // 0: hall.CPlayerOffline
	(*SPlayerOffline)(nil),     // 1: hall.SPlayerOffline
	(*CGameSettle)(nil),        // 2: hall.CGameSettle
	(*SGameSettle)(nil),        // 3: hall.SGameSettle
	(*datas.PBPlayerInfo)(nil), // 4: datas.PlayerInfo
}
var file_hall_hall_ss_proto_depIdxs = []int32{
	4, // 0: hall.CGameSettle.owner_player:type_name -> datas.PlayerInfo
	4, // 1: hall.CGameSettle.oppo_player:type_name -> datas.PlayerInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hall_hall_ss_proto_init() }
func file_hall_hall_ss_proto_init() {
	if File_hall_hall_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hall_hall_ss_proto_rawDesc), len(file_hall_hall_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hall_hall_ss_proto_goTypes,
		DependencyIndexes: file_hall_hall_ss_proto_depIdxs,
		MessageInfos:      file_hall_hall_ss_proto_msgTypes,
	}.Build()
	File_hall_hall_ss_proto = out.File
	file_hall_hall_ss_proto_goTypes = nil
	file_hall_hall_ss_proto_depIdxs = nil
}
