// Code generated by protoc-gen-gom. DO NOT EDIT.
package hall

import (
	context "context"
	rpc "github.com/fixkme/gokit/rpc"
	proto "google.golang.org/protobuf/proto"
)

type HallServer interface {
	EnterGame(context.Context, *CEnterGame) (*SEnterGame, error)
	GameSettle(context.Context, *CGameSettle) (*SGameSettle, error)
	LeaveGame(context.Context, *CLeaveGame) (*SLeaveGame, error)
	Login(context.Context, *CLogin) (*SLogin, error)
	PlayerOffline(context.Context, *CPlayerOffline) (*SPlayerOffline, error)
}

func RegisterHallServer(s rpc.ServiceRegistrar, srv HallServer) {
	s.RegisterService(&Hall_ServiceDesc, srv)
}

func _Hall_EnterGame_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CEnterGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(HallServer).EnterGame(ctx, req.(*CEnterGame))
	}
	return arg, h
}

func _Hall_GameSettle_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CGameSettle)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(HallServer).GameSettle(ctx, req.(*CGameSettle))
	}
	return arg, h
}

func _Hall_LeaveGame_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CLeaveGame)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(HallServer).LeaveGame(ctx, req.(*CLeaveGame))
	}
	return arg, h
}

func _Hall_Login_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CLogin)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(HallServer).Login(ctx, req.(*CLogin))
	}
	return arg, h
}

func _Hall_PlayerOffline_Materializer(srv any) (proto.Message, rpc.Handler) {
	arg := new(CPlayerOffline)
	h := func(ctx context.Context, req proto.Message) (proto.Message, error) {
		return srv.(HallServer).PlayerOffline(ctx, req.(*CPlayerOffline))
	}
	return arg, h
}

var Hall_ServiceDesc = rpc.ServiceDesc{
	ServiceName: "hall",
	HandlerType: (*HallServer)(nil),
	Methods: []rpc.MethodDesc{
		{
			MethodName: "EnterGame",
			Handler:    _Hall_EnterGame_Materializer,
		},
		{
			MethodName: "GameSettle",
			Handler:    _Hall_GameSettle_Materializer,
		},
		{
			MethodName: "LeaveGame",
			Handler:    _Hall_LeaveGame_Materializer,
		},
		{
			MethodName: "Login",
			Handler:    _Hall_Login_Materializer,
		},
		{
			MethodName: "PlayerOffline",
			Handler:    _Hall_PlayerOffline_Materializer,
		},
	},
}
