// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: hall/player.proto

package hall

import (
	datas "github.com/fixkme/othello/server/pb/datas"
	models "github.com/fixkme/othello/server/pb/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLogin) Reset() {
	*x = CLogin{}
	mi := &file_hall_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLogin) ProtoMessage() {}

func (x *CLogin) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLogin.ProtoReflect.Descriptor instead.
func (*CLogin) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{0}
}

func (x *CLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type SLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerData    *models.PBPlayerModel  `protobuf:"bytes,1,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"`
	ServerTz      int64                  `protobuf:"varint,2,opt,name=server_tz,json=serverTz,proto3" json:"server_tz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLogin) Reset() {
	*x = SLogin{}
	mi := &file_hall_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLogin) ProtoMessage() {}

func (x *SLogin) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLogin.ProtoReflect.Descriptor instead.
func (*SLogin) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{1}
}

func (x *SLogin) GetPlayerData() *models.PBPlayerModel {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

func (x *SLogin) GetServerTz() int64 {
	if x != nil {
		return x.ServerTz
	}
	return 0
}

type CEnterGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CEnterGame) Reset() {
	*x = CEnterGame{}
	mi := &file_hall_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CEnterGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CEnterGame) ProtoMessage() {}

func (x *CEnterGame) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CEnterGame.ProtoReflect.Descriptor instead.
func (*CEnterGame) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{2}
}

type SEnterGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableInfo     *datas.PBTableInfo     `protobuf:"bytes,1,opt,name=table_info,json=tableInfo,proto3" json:"table_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SEnterGame) Reset() {
	*x = SEnterGame{}
	mi := &file_hall_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SEnterGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEnterGame) ProtoMessage() {}

func (x *SEnterGame) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEnterGame.ProtoReflect.Descriptor instead.
func (*SEnterGame) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{3}
}

func (x *SEnterGame) GetTableInfo() *datas.PBTableInfo {
	if x != nil {
		return x.TableInfo
	}
	return nil
}

type PPlayerJoinGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerInfo    *datas.PBPlayerInfo    `protobuf:"bytes,1,opt,name=player_info,json=playerInfo,proto3" json:"player_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PPlayerJoinGame) Reset() {
	*x = PPlayerJoinGame{}
	mi := &file_hall_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PPlayerJoinGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PPlayerJoinGame) ProtoMessage() {}

func (x *PPlayerJoinGame) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PPlayerJoinGame.ProtoReflect.Descriptor instead.
func (*PPlayerJoinGame) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{4}
}

func (x *PPlayerJoinGame) GetPlayerInfo() *datas.PBPlayerInfo {
	if x != nil {
		return x.PlayerInfo
	}
	return nil
}

type CLeaveGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CLeaveGame) Reset() {
	*x = CLeaveGame{}
	mi := &file_hall_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CLeaveGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CLeaveGame) ProtoMessage() {}

func (x *CLeaveGame) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CLeaveGame.ProtoReflect.Descriptor instead.
func (*CLeaveGame) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{5}
}

type SLeaveGame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SLeaveGame) Reset() {
	*x = SLeaveGame{}
	mi := &file_hall_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SLeaveGame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SLeaveGame) ProtoMessage() {}

func (x *SLeaveGame) ProtoReflect() protoreflect.Message {
	mi := &file_hall_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SLeaveGame.ProtoReflect.Descriptor instead.
func (*SLeaveGame) Descriptor() ([]byte, []int) {
	return file_hall_player_proto_rawDescGZIP(), []int{6}
}

var File_hall_player_proto protoreflect.FileDescriptor

const file_hall_player_proto_rawDesc = "" +
	"\n" +
	"\x11hall/player.proto\x12\x04hall\x1a\x19models/player_model.proto\x1a\x17datas/player_data.proto\"\"\n" +
	"\x06CLogin\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"[\n" +
	"\x06SLogin\x124\n" +
	"\vplayer_data\x18\x01 \x01(\v2\x13.models.PlayerModelR\n" +
	"playerData\x12\x1b\n" +
	"\tserver_tz\x18\x02 \x01(\x03R\bserverTz\"\f\n" +
	"\n" +
	"CEnterGame\"=\n" +
	"\n" +
	"SEnterGame\x12/\n" +
	"\n" +
	"table_info\x18\x01 \x01(\v2\x10.datas.TableInfoR\ttableInfo\"E\n" +
	"\x0fPPlayerJoinGame\x122\n" +
	"\vplayer_info\x18\x01 \x01(\v2\x11.datas.PlayerInfoR\n" +
	"playerInfo\"\f\n" +
	"\n" +
	"CLeaveGame\"\f\n" +
	"\n" +
	"SLeaveGameB*Z(github.com/fixkme/othello/server/pb/hallb\x06proto3"

var (
	file_hall_player_proto_rawDescOnce sync.Once
	file_hall_player_proto_rawDescData []byte
)

func file_hall_player_proto_rawDescGZIP() []byte {
	file_hall_player_proto_rawDescOnce.Do(func() {
		file_hall_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hall_player_proto_rawDesc), len(file_hall_player_proto_rawDesc)))
	})
	return file_hall_player_proto_rawDescData
}

var file_hall_player_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hall_player_proto_goTypes = []any{
	(*CLogin)(nil),               // 0: hall.CLogin
	(*SLogin)(nil),               // 1: hall.SLogin
	(*CEnterGame)(nil),           // 2: hall.CEnterGame
	(*SEnterGame)(nil),           // 3: hall.SEnterGame
	(*PPlayerJoinGame)(nil),      // 4: hall.PPlayerJoinGame
	(*CLeaveGame)(nil),           // 5: hall.CLeaveGame
	(*SLeaveGame)(nil),           // 6: hall.SLeaveGame
	(*models.PBPlayerModel)(nil), // 7: models.PlayerModel
	(*datas.PBTableInfo)(nil),    // 8: datas.TableInfo
	(*datas.PBPlayerInfo)(nil),   // 9: datas.PlayerInfo
}
var file_hall_player_proto_depIdxs = []int32{
	7, // 0: hall.SLogin.player_data:type_name -> models.PlayerModel
	8, // 1: hall.SEnterGame.table_info:type_name -> datas.TableInfo
	9, // 2: hall.PPlayerJoinGame.player_info:type_name -> datas.PlayerInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_hall_player_proto_init() }
func file_hall_player_proto_init() {
	if File_hall_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hall_player_proto_rawDesc), len(file_hall_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hall_player_proto_goTypes,
		DependencyIndexes: file_hall_player_proto_depIdxs,
		MessageInfos:      file_hall_player_proto_msgTypes,
	}.Build()
	File_hall_player_proto = out.File
	file_hall_player_proto_goTypes = nil
	file_hall_player_proto_depIdxs = nil
}
