// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.27.1
// source: hall/player.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PlayerInfo, TableInfo } from "../datas/player_data";
import { PlayerModel } from "../models/player_model";
import { messageTypeRegistry } from "../typeRegistry";

export const protobufPackage = "hall";

export interface CLogin {
  $type: "hall.CLogin";
  account: string;
}

export interface SLogin {
  $type: "hall.SLogin";
  playerData: PlayerModel | undefined;
  serverTz: number;
}

export interface CEnterGame {
  $type: "hall.CEnterGame";
}

export interface SEnterGame {
  $type: "hall.SEnterGame";
  tableInfo: TableInfo | undefined;
}

export interface PPlayerJoinGame {
  $type: "hall.PPlayerJoinGame";
  playerInfo: PlayerInfo | undefined;
}

export interface CLeaveGame {
  $type: "hall.CLeaveGame";
}

export interface SLeaveGame {
  $type: "hall.SLeaveGame";
}

export interface CCheckTime {
  $type: "hall.CCheckTime";
}

export interface SCheckTime {
  $type: "hall.SCheckTime";
  ts: number;
}

function createBaseCLogin(): CLogin {
  return { $type: "hall.CLogin", account: "" };
}

export const CLogin: MessageFns<CLogin, "hall.CLogin"> = {
  $type: "hall.CLogin" as const,

  encode(message: CLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.account !== "") {
      writer.uint32(10).string(message.account);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.account = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CLogin {
    return { $type: CLogin.$type, account: isSet(object.account) ? globalThis.String(object.account) : "" };
  },

  toJSON(message: CLogin): unknown {
    const obj: any = {};
    if (message.account !== "") {
      obj.account = message.account;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CLogin>, I>>(base?: I): CLogin {
    return CLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CLogin>, I>>(object: I): CLogin {
    const message = createBaseCLogin();
    message.account = object.account ?? "";
    return message;
  },
};

messageTypeRegistry.set(CLogin.$type, CLogin);

function createBaseSLogin(): SLogin {
  return { $type: "hall.SLogin", playerData: undefined, serverTz: 0 };
}

export const SLogin: MessageFns<SLogin, "hall.SLogin"> = {
  $type: "hall.SLogin" as const,

  encode(message: SLogin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerData !== undefined) {
      PlayerModel.encode(message.playerData, writer.uint32(10).fork()).join();
    }
    if (message.serverTz !== 0) {
      writer.uint32(16).int64(message.serverTz);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SLogin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSLogin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerData = PlayerModel.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.serverTz = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SLogin {
    return {
      $type: SLogin.$type,
      playerData: isSet(object.playerData) ? PlayerModel.fromJSON(object.playerData) : undefined,
      serverTz: isSet(object.serverTz) ? globalThis.Number(object.serverTz) : 0,
    };
  },

  toJSON(message: SLogin): unknown {
    const obj: any = {};
    if (message.playerData !== undefined) {
      obj.playerData = PlayerModel.toJSON(message.playerData);
    }
    if (message.serverTz !== 0) {
      obj.serverTz = Math.round(message.serverTz);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SLogin>, I>>(base?: I): SLogin {
    return SLogin.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SLogin>, I>>(object: I): SLogin {
    const message = createBaseSLogin();
    message.playerData = (object.playerData !== undefined && object.playerData !== null)
      ? PlayerModel.fromPartial(object.playerData)
      : undefined;
    message.serverTz = object.serverTz ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SLogin.$type, SLogin);

function createBaseCEnterGame(): CEnterGame {
  return { $type: "hall.CEnterGame" };
}

export const CEnterGame: MessageFns<CEnterGame, "hall.CEnterGame"> = {
  $type: "hall.CEnterGame" as const,

  encode(_: CEnterGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CEnterGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCEnterGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CEnterGame {
    return { $type: CEnterGame.$type };
  },

  toJSON(_: CEnterGame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CEnterGame>, I>>(base?: I): CEnterGame {
    return CEnterGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CEnterGame>, I>>(_: I): CEnterGame {
    const message = createBaseCEnterGame();
    return message;
  },
};

messageTypeRegistry.set(CEnterGame.$type, CEnterGame);

function createBaseSEnterGame(): SEnterGame {
  return { $type: "hall.SEnterGame", tableInfo: undefined };
}

export const SEnterGame: MessageFns<SEnterGame, "hall.SEnterGame"> = {
  $type: "hall.SEnterGame" as const,

  encode(message: SEnterGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tableInfo !== undefined) {
      TableInfo.encode(message.tableInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SEnterGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSEnterGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tableInfo = TableInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SEnterGame {
    return {
      $type: SEnterGame.$type,
      tableInfo: isSet(object.tableInfo) ? TableInfo.fromJSON(object.tableInfo) : undefined,
    };
  },

  toJSON(message: SEnterGame): unknown {
    const obj: any = {};
    if (message.tableInfo !== undefined) {
      obj.tableInfo = TableInfo.toJSON(message.tableInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SEnterGame>, I>>(base?: I): SEnterGame {
    return SEnterGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SEnterGame>, I>>(object: I): SEnterGame {
    const message = createBaseSEnterGame();
    message.tableInfo = (object.tableInfo !== undefined && object.tableInfo !== null)
      ? TableInfo.fromPartial(object.tableInfo)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(SEnterGame.$type, SEnterGame);

function createBasePPlayerJoinGame(): PPlayerJoinGame {
  return { $type: "hall.PPlayerJoinGame", playerInfo: undefined };
}

export const PPlayerJoinGame: MessageFns<PPlayerJoinGame, "hall.PPlayerJoinGame"> = {
  $type: "hall.PPlayerJoinGame" as const,

  encode(message: PPlayerJoinGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.playerInfo !== undefined) {
      PlayerInfo.encode(message.playerInfo, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PPlayerJoinGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePPlayerJoinGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.playerInfo = PlayerInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PPlayerJoinGame {
    return {
      $type: PPlayerJoinGame.$type,
      playerInfo: isSet(object.playerInfo) ? PlayerInfo.fromJSON(object.playerInfo) : undefined,
    };
  },

  toJSON(message: PPlayerJoinGame): unknown {
    const obj: any = {};
    if (message.playerInfo !== undefined) {
      obj.playerInfo = PlayerInfo.toJSON(message.playerInfo);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PPlayerJoinGame>, I>>(base?: I): PPlayerJoinGame {
    return PPlayerJoinGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PPlayerJoinGame>, I>>(object: I): PPlayerJoinGame {
    const message = createBasePPlayerJoinGame();
    message.playerInfo = (object.playerInfo !== undefined && object.playerInfo !== null)
      ? PlayerInfo.fromPartial(object.playerInfo)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(PPlayerJoinGame.$type, PPlayerJoinGame);

function createBaseCLeaveGame(): CLeaveGame {
  return { $type: "hall.CLeaveGame" };
}

export const CLeaveGame: MessageFns<CLeaveGame, "hall.CLeaveGame"> = {
  $type: "hall.CLeaveGame" as const,

  encode(_: CLeaveGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CLeaveGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCLeaveGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CLeaveGame {
    return { $type: CLeaveGame.$type };
  },

  toJSON(_: CLeaveGame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CLeaveGame>, I>>(base?: I): CLeaveGame {
    return CLeaveGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CLeaveGame>, I>>(_: I): CLeaveGame {
    const message = createBaseCLeaveGame();
    return message;
  },
};

messageTypeRegistry.set(CLeaveGame.$type, CLeaveGame);

function createBaseSLeaveGame(): SLeaveGame {
  return { $type: "hall.SLeaveGame" };
}

export const SLeaveGame: MessageFns<SLeaveGame, "hall.SLeaveGame"> = {
  $type: "hall.SLeaveGame" as const,

  encode(_: SLeaveGame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SLeaveGame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSLeaveGame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SLeaveGame {
    return { $type: SLeaveGame.$type };
  },

  toJSON(_: SLeaveGame): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SLeaveGame>, I>>(base?: I): SLeaveGame {
    return SLeaveGame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SLeaveGame>, I>>(_: I): SLeaveGame {
    const message = createBaseSLeaveGame();
    return message;
  },
};

messageTypeRegistry.set(SLeaveGame.$type, SLeaveGame);

function createBaseCCheckTime(): CCheckTime {
  return { $type: "hall.CCheckTime" };
}

export const CCheckTime: MessageFns<CCheckTime, "hall.CCheckTime"> = {
  $type: "hall.CCheckTime" as const,

  encode(_: CCheckTime, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CCheckTime {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCCheckTime();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CCheckTime {
    return { $type: CCheckTime.$type };
  },

  toJSON(_: CCheckTime): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CCheckTime>, I>>(base?: I): CCheckTime {
    return CCheckTime.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CCheckTime>, I>>(_: I): CCheckTime {
    const message = createBaseCCheckTime();
    return message;
  },
};

messageTypeRegistry.set(CCheckTime.$type, CCheckTime);

function createBaseSCheckTime(): SCheckTime {
  return { $type: "hall.SCheckTime", ts: 0 };
}

export const SCheckTime: MessageFns<SCheckTime, "hall.SCheckTime"> = {
  $type: "hall.SCheckTime" as const,

  encode(message: SCheckTime, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ts !== 0) {
      writer.uint32(8).int64(message.ts);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SCheckTime {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSCheckTime();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ts = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SCheckTime {
    return { $type: SCheckTime.$type, ts: isSet(object.ts) ? globalThis.Number(object.ts) : 0 };
  },

  toJSON(message: SCheckTime): unknown {
    const obj: any = {};
    if (message.ts !== 0) {
      obj.ts = Math.round(message.ts);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SCheckTime>, I>>(base?: I): SCheckTime {
    return SCheckTime.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SCheckTime>, I>>(object: I): SCheckTime {
    const message = createBaseSCheckTime();
    message.ts = object.ts ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SCheckTime.$type, SCheckTime);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
