// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.1
// source: gate/gate_ss.proto

package gate

import (
	ws "github.com/fixkme/othello/server/pb/ws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通知单个玩家
type CNoticePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Notices       []*ws.PBPackage        `protobuf:"bytes,2,rep,name=notices,proto3" json:"notices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CNoticePlayer) Reset() {
	*x = CNoticePlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CNoticePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CNoticePlayer) ProtoMessage() {}

func (x *CNoticePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CNoticePlayer.ProtoReflect.Descriptor instead.
func (*CNoticePlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{0}
}

func (x *CNoticePlayer) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *CNoticePlayer) GetNotices() []*ws.PBPackage {
	if x != nil {
		return x.Notices
	}
	return nil
}

type SNoticePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SNoticePlayer) Reset() {
	*x = SNoticePlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SNoticePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SNoticePlayer) ProtoMessage() {}

func (x *SNoticePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SNoticePlayer.ProtoReflect.Descriptor instead.
func (*SNoticePlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{1}
}

// 广播给多个玩家
type CBroadcastPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerIds     []int64                `protobuf:"varint,1,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Notices       []*ws.PBPackage        `protobuf:"bytes,2,rep,name=notices,proto3" json:"notices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CBroadcastPlayer) Reset() {
	*x = CBroadcastPlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CBroadcastPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CBroadcastPlayer) ProtoMessage() {}

func (x *CBroadcastPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CBroadcastPlayer.ProtoReflect.Descriptor instead.
func (*CBroadcastPlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{2}
}

func (x *CBroadcastPlayer) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *CBroadcastPlayer) GetNotices() []*ws.PBPackage {
	if x != nil {
		return x.Notices
	}
	return nil
}

type SBroadcastPlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBroadcastPlayer) Reset() {
	*x = SBroadcastPlayer{}
	mi := &file_gate_gate_ss_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBroadcastPlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBroadcastPlayer) ProtoMessage() {}

func (x *SBroadcastPlayer) ProtoReflect() protoreflect.Message {
	mi := &file_gate_gate_ss_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBroadcastPlayer.ProtoReflect.Descriptor instead.
func (*SBroadcastPlayer) Descriptor() ([]byte, []int) {
	return file_gate_gate_ss_proto_rawDescGZIP(), []int{3}
}

var File_gate_gate_ss_proto protoreflect.FileDescriptor

const file_gate_gate_ss_proto_rawDesc = "" +
	"\n" +
	"\x12gate/gate_ss.proto\x12\x04gate\x1a\vws/ws.proto\"U\n" +
	"\rCNoticePlayer\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12'\n" +
	"\anotices\x18\x02 \x03(\v2\r.ws.PBPackageR\anotices\"\x0f\n" +
	"\rSNoticePlayer\"Z\n" +
	"\x10CBroadcastPlayer\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x01 \x03(\x03R\tplayerIds\x12'\n" +
	"\anotices\x18\x02 \x03(\v2\r.ws.PBPackageR\anotices\"\x12\n" +
	"\x10SBroadcastPlayerB*Z(github.com/fixkme/othello/server/pb/gateb\x06proto3"

var (
	file_gate_gate_ss_proto_rawDescOnce sync.Once
	file_gate_gate_ss_proto_rawDescData []byte
)

func file_gate_gate_ss_proto_rawDescGZIP() []byte {
	file_gate_gate_ss_proto_rawDescOnce.Do(func() {
		file_gate_gate_ss_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_gate_ss_proto_rawDesc), len(file_gate_gate_ss_proto_rawDesc)))
	})
	return file_gate_gate_ss_proto_rawDescData
}

var file_gate_gate_ss_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gate_gate_ss_proto_goTypes = []any{
	(*CNoticePlayer)(nil),    // 0: gate.CNoticePlayer
	(*SNoticePlayer)(nil),    // 1: gate.SNoticePlayer
	(*CBroadcastPlayer)(nil), // 2: gate.CBroadcastPlayer
	(*SBroadcastPlayer)(nil), // 3: gate.SBroadcastPlayer
	(*ws.PBPackage)(nil),     // 4: ws.PBPackage
}
var file_gate_gate_ss_proto_depIdxs = []int32{
	4, // 0: gate.CNoticePlayer.notices:type_name -> ws.PBPackage
	4, // 1: gate.CBroadcastPlayer.notices:type_name -> ws.PBPackage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_gate_gate_ss_proto_init() }
func file_gate_gate_ss_proto_init() {
	if File_gate_gate_ss_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_gate_ss_proto_rawDesc), len(file_gate_gate_ss_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_gate_ss_proto_goTypes,
		DependencyIndexes: file_gate_gate_ss_proto_depIdxs,
		MessageInfos:      file_gate_gate_ss_proto_msgTypes,
	}.Build()
	File_gate_gate_ss_proto = out.File
	file_gate_gate_ss_proto_goTypes = nil
	file_gate_gate_ss_proto_depIdxs = nil
}
